language: csharp  
sudo: required  
dist: trusty  
env:  
  - CLI_VERSION=latest
mono:  
  - 5.10.0
dotnet:  2.1.400
os:  
  - linux
branches:  
  only:
    - master
    - /.*/
before_script:
- chmod +x ./build.sh
before_install:
  - git submodule update --init --recursive
  - sudo apt install nuget
script:  
  - ./build.sh
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1